# Generated by Django 5.0.2 on 2024-02-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='deposit',
            field=models.IntegerField(default=0),
        ),
    ]
